#!/usr/bin/env bash
# worktree.sh — Create and manage git worktrees for parallel pipeline work
#
# Usage:
#   ./.claude/scripts/worktree.sh create <pipeline>
#   ./.claude/scripts/worktree.sh remove <pipeline>
#   ./.claude/scripts/worktree.sh list [pipeline]
#
# <pipeline> is the kebab-case pipeline name (e.g., "session-notes")
#
# Each pipeline gets a SINGLE worktree of the entire repo at .worktrees/<pipeline>/.
# One branch, one checkout, all projects included.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ALLOC="${ROOT}/.claude/scripts/alloc-ports.sh"

cmd_create() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    echo "Worktree already exists: $worktree_dir"
    "$ALLOC" alloc "$pipeline"
    exit 0
  fi

  if ! git rev-parse --verify "$branch" >/dev/null 2>&1; then
    git branch "$branch" main
  fi

  git worktree add "$worktree_dir" "$branch"

  # === Per-project setup — EDIT FOR YOUR STACK ===
  # For each subproject, run whatever bootstraps a fresh checkout — install
  # dependencies, generate types/codegen, copy env files, etc. The script just
  # needs to leave a runnable checkout behind. Pin lockfiles for reproducibility.
  # If install is expensive, symlink the dependency cache from the main checkout
  # instead of reinstalling.
  #
  # Pattern (one block per subproject):
  #
  # if [ -f "${worktree_dir}/{project-dir}/{project-marker-file}" ]; then
  #   (cd "${worktree_dir}/{project-dir}" && {your install command}) || true
  # fi

  # Allocate unique ports
  local ports
  ports=$("$ALLOC" alloc "$pipeline")

  # Parse the port allocation output (KEY=VALUE per line).
  # Add one parse line per port your alloc-ports.sh emits.
  local port_a port_b port_c
  port_a=$(echo "$ports" | grep '^PORT_A=' | cut -d= -f2)
  port_b=$(echo "$ports" | grep '^PORT_B=' | cut -d= -f2)
  port_c=$(echo "$ports" | grep '^PORT_C=' | cut -d= -f2)

  # Write .env.ports into the worktree root (agents source this)
  cat > "${worktree_dir}/.env.ports" <<ENVEOF
# Auto-generated by worktree.sh — unique ports for pipeline: ${pipeline}
PORT_A=${port_a}
PORT_B=${port_b}
PORT_C=${port_c}
ENVEOF

  # === Per-project env-file rewriting — EDIT FOR YOUR STACK ===
  # Copy .env.local / .env.test (or your equivalents) from main into the
  # worktree, substituting port numbers so parallel pipelines don't collide.
  # Pattern: sed-replace the port in connection strings / PORT= lines / etc.
  #
  # Pattern (one block per env file you maintain):
  #
  # if [ -f "${ROOT}/{project-dir}/.env.test" ]; then
  #   sed \
  #     -e "s/^PORT=.*/PORT=${port_a}/" \
  #     -e "s|{old-host}:[0-9]*|{old-host}:${port_c}|" \
  #     "${ROOT}/{project-dir}/.env.test" > "${worktree_dir}/{project-dir}/.env.test"
  # fi

  echo "Worktree ready: $worktree_dir"
  echo "Branch: $branch"
  echo "API_PORT=${api_port}"
  echo "WEB_PORT=${web_port}"
  echo "TEST_DB_PORT=${test_db_port}"
}

cmd_remove() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    git worktree remove "$worktree_dir" --force 2>/dev/null || true
    echo "Worktree removed: $worktree_dir"
  else
    echo "No worktree found: $worktree_dir"
  fi

  git branch -d "$branch" 2>/dev/null || true

  "$ALLOC" free "$pipeline"

  echo "Pipeline cleaned up: $pipeline"
}

cmd_list() {
  local pipeline="${1:-}"

  if [ -n "$pipeline" ]; then
    local worktree_dir="${ROOT}/.worktrees/${pipeline}"
    if [ ! -d "$worktree_dir" ]; then
      echo "No worktree for pipeline: $pipeline"
      return 0
    fi
    echo "=== Pipeline: $pipeline ==="
    echo "  Branch: pipeline/$pipeline"
    echo "  Path: $worktree_dir"
    if [ -f "$worktree_dir/.env.ports" ]; then
      echo "  Ports:"
      grep -E '^[A-Z_]+_PORT=' "$worktree_dir/.env.ports" | sed 's/^/    /'
    fi
  else
    echo "=== Active Pipelines ==="
    for d in "${ROOT}/.worktrees"/*/; do
      local name
      name="$(basename "$d")"
      [[ "$name" == .* ]] && continue
      [ -d "$d" ] || continue
      echo "  $name/ → pipeline/$name"
    done
  fi

  echo ""
  echo "=== Port Allocations ==="
  "$ALLOC" list
}

case "${1:-help}" in
  create)  cmd_create "${2:?pipeline required}" ;;
  remove)  cmd_remove "${2:?pipeline required}" ;;
  list)    cmd_list   "${2:-}" ;;
  *)
    echo "Usage: $0 {create|remove|list} <pipeline>"
    exit 1
    ;;
esac
