#!/usr/bin/env bash
# worktree.sh — Create and manage git worktrees for parallel pipeline work
#
# Usage:
#   ./.claude/scripts/worktree.sh create <pipeline>
#   ./.claude/scripts/worktree.sh remove <pipeline>
#   ./.claude/scripts/worktree.sh list [pipeline]
#   ./.claude/scripts/worktree.sh prune          # remove orphaned worktree dirs
#
# <pipeline> is the kebab-case pipeline name (e.g., "session-notes")
#
# Monorepo: each pipeline gets a SINGLE worktree of the entire repo at
# .worktrees/<pipeline>/. One branch, one checkout, all projects included.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ALLOC="${ROOT}/.claude/scripts/alloc-ports.sh"

cmd_create() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    echo "Worktree already exists: $worktree_dir"
    # Still print ports for convenience
    "$ALLOC" alloc "$pipeline"
    exit 0
  fi

  # Create branch from main if it doesn't exist
  if ! git rev-parse --verify "$branch" >/dev/null 2>&1; then
    git branch "$branch" main
  fi

  # Create worktree — full monorepo checkout
  git worktree add "$worktree_dir" "$branch"

  # Install dependencies for each project
  # Backend ({BE_PKG_MGR})
  if [ -f "${worktree_dir}/{BACKEND_PROJECT}/package.json" ]; then
    (cd "${worktree_dir}/{BACKEND_PROJECT}" && {BE_PKG_MGR} install --frozen-lockfile) || true
  fi

  # {AI_SERVICE_NAME} ({AI_PKG_MGR})
  if [ -f "${worktree_dir}/{AI_PROJECT}/pyproject.toml" ]; then
    (cd "${worktree_dir}/{AI_PROJECT}" && {AI_PKG_MGR} sync 2>/dev/null) || true
  fi

  # Frontend (symlink node_modules from main checkout)
  if [ -d "${ROOT}/{FRONTEND_PROJECT}/node_modules" ]; then
    ln -sfn "${ROOT}/{FRONTEND_PROJECT}/node_modules" "${worktree_dir}/{FRONTEND_PROJECT}/node_modules"
  fi

  # Web (npm — marketing site)
  if [ -f "${worktree_dir}/{WEB_PROJECT}/package.json" ]; then
    if [ -d "${ROOT}/{WEB_PROJECT}/node_modules" ]; then
      ln -sfn "${ROOT}/{WEB_PROJECT}/node_modules" "${worktree_dir}/{WEB_PROJECT}/node_modules"
    else
      (cd "${worktree_dir}/{WEB_PROJECT}" && npm install) || true
    fi
  fi

  # Infrastructure: nothing to install

  # Allocate unique ports (one allocation per pipeline)
  local ports
  ports=$("$ALLOC" alloc "$pipeline")
  local be_port fe_port test_pg_port test_ls_port pulse_port web_port cortex_port
  be_port=$(echo "$ports" | grep BE_PORT | cut -d= -f2)
  fe_port=$(echo "$ports" | grep FE_PORT | cut -d= -f2)
  test_pg_port=$(echo "$ports" | grep TEST_PG_PORT | cut -d= -f2)
  test_ls_port=$(echo "$ports" | grep TEST_LS_PORT | cut -d= -f2)
  pulse_port=$(echo "$ports" | grep PULSE_PORT | cut -d= -f2)
  web_port=$(echo "$ports" | grep WEB_PORT | cut -d= -f2)
  cortex_port=$(echo "$ports" | grep CORTEX_PORT | cut -d= -f2)

  # Write .env.ports into the worktree root (agents source this)
  cat > "${worktree_dir}/.env.ports" <<ENVEOF
# Auto-generated by worktree.sh — unique ports for pipeline: ${pipeline}
# Backend server port
BE_PORT=${be_port}
# Frontend dev server port
FE_PORT=${fe_port}
# Backend URL for frontend proxy
VITE_BACKEND_PORT=${be_port}
VITE_PORT=${fe_port}
# Pipeline-isolated test infrastructure ports
TEST_PG_PORT=${test_pg_port}
TEST_LS_PORT=${test_ls_port}
# Pulse (analytics) port
PULSE_PORT=${pulse_port}
# Web (marketing site) port
WEB_PORT=${web_port}
# {AI_SERVICE_NAME} HTTP server port
CORTEX_PORT=${cortex_port}
ENVEOF

  # Copy .env.local for web (standalone — reads public env vars at build time)
  if [ -f "${ROOT}/{WEB_PROJECT}/.env.local" ]; then
    cp "${ROOT}/{WEB_PROJECT}/.env.local" "${worktree_dir}/{WEB_PROJECT}/.env.local"
  fi

  # Copy and override .env.local/.env.test for backend
  if [ -f "${ROOT}/{BACKEND_PROJECT}/.env.local" ]; then
    sed "s/^PORT=.*/PORT=${be_port}/" "${ROOT}/{BACKEND_PROJECT}/.env.local" > "${worktree_dir}/{BACKEND_PROJECT}/.env.local"
  fi
  if [ -f "${ROOT}/{BACKEND_PROJECT}/.env.test" ]; then
    sed \
      -e "s|postgresql://postgres@localhost:[0-9]*/{PROJECT_NAME_LOWER}_test|postgresql://postgres@localhost:${test_pg_port}/{PROJECT_NAME_LOWER}_test|" \
      -e "s/^PORT=.*/PORT=${be_port}/" \
      "${ROOT}/{BACKEND_PROJECT}/.env.test" > "${worktree_dir}/{BACKEND_PROJECT}/.env.test"
  fi

  # Copy .env.local for {AI_SERVICE_NAME} — inject CORTEX_PORT for HTTP server
  if [ -f "${ROOT}/{AI_PROJECT}/.env.local" ]; then
    if grep -q "^CORTEX_PORT=" "${ROOT}/{AI_PROJECT}/.env.local"; then
      sed "s/^CORTEX_PORT=.*/CORTEX_PORT=${cortex_port}/" "${ROOT}/{AI_PROJECT}/.env.local" > "${worktree_dir}/{AI_PROJECT}/.env.local"
    else
      cp "${ROOT}/{AI_PROJECT}/.env.local" "${worktree_dir}/{AI_PROJECT}/.env.local"
      echo "CORTEX_PORT=${cortex_port}" >> "${worktree_dir}/{AI_PROJECT}/.env.local"
    fi
  fi
  if [ -f "${ROOT}/{AI_PROJECT}/.env.test" ]; then
    local cortex_env_test="${worktree_dir}/{AI_PROJECT}/.env.test"
    sed \
      -e "s|postgresql+asyncpg://postgres:postgres@localhost:[0-9]*/{PROJECT_NAME_LOWER}_test|postgresql+asyncpg://postgres:postgres@localhost:${test_pg_port}/{PROJECT_NAME_LOWER}_test|" \
      -e "s|http://localhost:[0-9]*/|http://localhost:${test_ls_port}/|g" \
      -e "s|localhost\.localstack\.cloud:[0-9]*/|localhost.localstack.cloud:${test_ls_port}/|g" \
      "${ROOT}/{AI_PROJECT}/.env.test" > "$cortex_env_test"
    # Inject or override CORTEX_PORT
    if grep -q "^CORTEX_PORT=" "$cortex_env_test"; then
      sed -i '' "s/^CORTEX_PORT=.*/CORTEX_PORT=${cortex_port}/" "$cortex_env_test"
    else
      echo "CORTEX_PORT=${cortex_port}" >> "$cortex_env_test"
    fi
  fi

  echo "Worktree ready: $worktree_dir"
  echo "Branch: $branch"
  echo "BE_PORT=${be_port}"
  echo "FE_PORT=${fe_port}"
  echo "TEST_PG_PORT=${test_pg_port}"
  echo "TEST_LS_PORT=${test_ls_port}"
  echo "PULSE_PORT=${pulse_port}"
  echo "WEB_PORT=${web_port}"
  echo "CORTEX_PORT=${cortex_port}"
}

cmd_remove() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    git worktree remove "$worktree_dir" --force 2>/dev/null || true
    echo "Worktree removed: $worktree_dir"
  else
    echo "No worktree found: $worktree_dir"
  fi

  git branch -d "$branch" 2>/dev/null || true

  # Free port allocation
  "$ALLOC" free "$pipeline"

  # Tear down the pipeline's docker test stack (containers + volumes)
  make -C "${ROOT}/{INFRA_PROJECT}" {INFRA_NUKE_TARGET} PIPELINE="$pipeline" 2>/dev/null || true

  echo "Pipeline cleaned up: $pipeline"
}

cmd_prune() {
  # Remove ORPHANED worktree directories: present on disk but not a registered
  # git worktree AND with no active pipeline docs. Registered-but-inactive
  # worktrees are reported, never auto-removed (may hold uncommitted work).
  git -C "$ROOT" worktree prune 2>/dev/null || true  # drop git records for vanished dirs

  # Registered worktree BASENAMES — matched by name, not full path, so a symlinked or
  # canonicalized repo path can't misclassify a live worktree as orphaned.
  # Fail-safe: if git can't list worktrees, prune nothing rather than risk a live one.
  local registered
  if ! registered="$(git -C "$ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree /{n=split($2,a,"/"); print a[n]}')"; then
    echo "Prune skipped: could not list git worktrees."
    return 0
  fi

  local pruned=0
  for d in "${ROOT}/.worktrees"/*/; do
    [ -d "$d" ] || continue
    local name
    name="$(basename "$d")"
    [[ "$name" == .* ]] && continue

    if printf '%s\n' "$registered" | grep -qx "$name"; then
      # Registered worktree with no active pipeline → possible abandon. Report only.
      [ -d "${ROOT}/docs/dev/builds/${name}" ] || echo "REGISTERED-NO-DOCS: $name (registered worktree, no active pipeline — inspect; not auto-removed)"
      continue
    fi

    # Unregistered leftover directory
    if [ -d "${ROOT}/docs/dev/builds/${name}" ]; then
      echo "SKIP: $name (unregistered but has pipeline docs — inspect manually)"
      continue
    fi

    rm -rf "$d"
    "$ALLOC" free "$name" 2>/dev/null || true
    make -C "${ROOT}/{INFRA_PROJECT}" {INFRA_NUKE_TARGET} PIPELINE="$name" 2>/dev/null || true
    echo "PRUNED: $name (orphaned worktree dir)"
    pruned=$((pruned + 1))
  done
  echo "Prune complete: $pruned orphaned worktree(s) removed."
}

cmd_list() {
  local pipeline="${1:-}"

  if [ -n "$pipeline" ]; then
    local worktree_dir="${ROOT}/.worktrees/${pipeline}"
    if [ ! -d "$worktree_dir" ]; then
      echo "No worktree for pipeline: $pipeline"
      return 0
    fi
    echo "=== Pipeline: $pipeline ==="
    echo "  Branch: pipeline/$pipeline"
    echo "  Path: $worktree_dir"
    if [ -f "$worktree_dir/.env.ports" ]; then
      echo "  Ports:"
      grep -E '^(BE_PORT|FE_PORT|TEST_PG_PORT|TEST_LS_PORT|PULSE_PORT|WEB_PORT|CORTEX_PORT)=' "$worktree_dir/.env.ports" | sed 's/^/    /'
    fi
  else
    echo "=== Active Pipelines ==="
    for d in "${ROOT}/.worktrees"/*/; do
      local name
      name="$(basename "$d")"
      # Skip hidden dirs (.ports, .merge-lock, etc.)
      [[ "$name" == .* ]] && continue
      [ -d "$d" ] || continue
      echo "  $name/ → pipeline/$name"
    done
  fi

  echo ""
  echo "=== Port Allocations ==="
  "$ALLOC" list
}

case "${1:-help}" in
  create)  cmd_create "${2:?pipeline required}" ;;
  remove)  cmd_remove "${2:?pipeline required}" ;;
  list)    cmd_list   "${2:-}" ;;
  prune)   cmd_prune ;;
  *)
    echo "Usage: $0 {create|remove|list|prune} <pipeline>"
    exit 1
    ;;
esac
