#!/usr/bin/env bash
# worktree.sh — Create and manage git worktrees for parallel pipeline work
#
# Usage:
#   ./.claude/scripts/worktree.sh create <pipeline>
#   ./.claude/scripts/worktree.sh remove <pipeline>
#   ./.claude/scripts/worktree.sh list [pipeline]
#   ./.claude/scripts/worktree.sh prune          # remove orphaned worktree dirs
#
# <pipeline> is the kebab-case pipeline name (e.g., "session-notes")
#
# Each pipeline gets a SINGLE worktree of the entire repo at .worktrees/<pipeline>/.
# One branch, one checkout, every project in the roster included. At roster size 1
# the worktree IS the repo root (no per-project subdir).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ALLOC="${ROOT}/.claude/scripts/alloc-ports.sh"

# ─── Project roster ───────────────────────────────────────────────
# SETUP fills this from the install interview — one entry per project, in order.
# Each entry is a pipe-delimited record:
#
#   dir | install_kind | install_cmd | env_files
#
#   dir          — project directory relative to repo root. "." for a single-project
#                  repo (the worktree root IS the project; no subdir).
#   install_kind — how deps are provisioned in the worktree:
#                    install  — run install_cmd inside the worktree
#                    symlink  — symlink node_modules from the main checkout
#                               (falls back to install_cmd if main has none)
#                    none     — nothing to install (e.g. an infra project)
#   install_cmd  — the command run in the project dir to install deps
#                  (e.g. "pnpm install --frozen-lockfile", "uv sync", "npm install")
#   env_files    — space-separated env filenames to copy from main into the worktree
#                  with this project's port substituted (".env.local .env.test"),
#                  or "-" for none.
#
# Single-project collapse: a roster of one entry with dir "." targets the repo root.
PROJECTS=(
  # {PROJECT_ROSTER} — SETUP expands one line per roster entry, e.g.:
  # "{project}|{INSTALL_KIND}|{PROJECT_INSTALL_CMD}|{PROJECT_ENV_FILES}"
)

# Resolve a project's path inside a target tree. At roster size 1 the entry's dir
# is ".", so the path collapses to the tree root with no trailing subdir.
proj_path() {
  local base="$1" dir="$2"
  if [ "$dir" = "." ]; then
    echo "$base"
  else
    echo "${base}/${dir}"
  fi
}

cmd_create() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    echo "Worktree already exists: $worktree_dir"
    # Still print ports for convenience
    "$ALLOC" alloc "$pipeline"
    exit 0
  fi

  # Create branch from main if it doesn't exist
  if ! git rev-parse --verify "$branch" >/dev/null 2>&1; then
    git branch "$branch" main
  fi

  # Create worktree — full repo checkout
  git worktree add "$worktree_dir" "$branch"

  # Install dependencies for each project in the roster
  local entry dir install_kind install_cmd env_files src_path dst_path
  for entry in "${PROJECTS[@]}"; do
    IFS='|' read -r dir install_kind install_cmd env_files <<< "$entry"
    src_path="$(proj_path "$ROOT" "$dir")"
    dst_path="$(proj_path "$worktree_dir" "$dir")"
    case "$install_kind" in
      install)
        if [ -n "$install_cmd" ]; then
          (cd "$dst_path" && eval "$install_cmd" 2>/dev/null) || true
        fi
        ;;
      symlink)
        # Reuse main's node_modules when present; otherwise install fresh.
        if [ -d "${src_path}/node_modules" ]; then
          ln -sfn "${src_path}/node_modules" "${dst_path}/node_modules"
        elif [ -n "$install_cmd" ]; then
          (cd "$dst_path" && eval "$install_cmd") || true
        fi
        ;;
      none) : ;;  # nothing to install
    esac
  done

  # Allocate unique ports (one allocation per pipeline)
  local ports
  ports=$("$ALLOC" alloc "$pipeline")
  local be_port fe_port test_pg_port test_ls_port pulse_port web_port cortex_port
  be_port=$(echo "$ports" | grep BE_PORT | cut -d= -f2)
  fe_port=$(echo "$ports" | grep FE_PORT | cut -d= -f2)
  test_pg_port=$(echo "$ports" | grep TEST_PG_PORT | cut -d= -f2)
  test_ls_port=$(echo "$ports" | grep TEST_LS_PORT | cut -d= -f2)
  pulse_port=$(echo "$ports" | grep PULSE_PORT | cut -d= -f2)
  web_port=$(echo "$ports" | grep WEB_PORT | cut -d= -f2)
  cortex_port=$(echo "$ports" | grep CORTEX_PORT | cut -d= -f2)

  # Write .env.ports into the worktree root (agents source this)
  cat > "${worktree_dir}/.env.ports" <<ENVEOF
# Auto-generated by worktree.sh — unique ports for pipeline: ${pipeline}
# Backend server port
BE_PORT=${be_port}
# Frontend dev server port
FE_PORT=${fe_port}
# Backend URL for frontend proxy
VITE_BACKEND_PORT=${be_port}
VITE_PORT=${fe_port}
# Pipeline-isolated test infrastructure ports
TEST_PG_PORT=${test_pg_port}
TEST_LS_PORT=${test_ls_port}
# Pulse (analytics) port
PULSE_PORT=${pulse_port}
# Web (marketing site) port
WEB_PORT=${web_port}
# {AI_SERVICE_NAME} HTTP server port
CORTEX_PORT=${cortex_port}
ENVEOF

  # Copy per-project env files, substituting allocated ports.
  # SETUP expands one block per roster entry that declares env_files — the port
  # substitution rules are project-specific, so they materialize per entry rather
  # than from the array. A single-project repo gets one block targeting the root.
  #
  # .env.test coherence (CRITICAL): when a project's test harness reads its
  # connection target verbatim from .env.test, the rewrite must retarget EVERY
  # test-port reference to the pipeline-isolated stack — not just the DB URL but
  # also the DB port and ALL data-store/queue service endpoints ({TECH_STACK_PLACEHOLDER}
  # object-store + queue URLs). Leaving any one on the shared {PORT_B}/{PORT_B} stack
  # silently pins that project (and any sibling whose e2e tier reads the same file)
  # onto the default stack, causing cross-pipeline collisions. The rewrite rules:
  #   • ^-anchored — so an endpoint rewrite never touches a cross-service URL
  #     (e.g. a {project}→{project} callback URL, or a non-test HOST/comment line);
  #   • password-agnostic — match the DB URL without assuming a `user:pass@` form,
  #     since a credential-less `user@host` URL must rewrite too;
  #   • slash-agnostic — match the endpoint with or without a trailing slash,
  #     since committed values may carry none.
  # SETUP materializes one such block per roster entry with env_files, e.g.:
  #
  #   if [ -f "$(proj_path "$ROOT" "{project}")/.env.test" ]; then
  #     sed \
  #       -e "s|@localhost:[0-9]*/{TEST_DB_NAME}|@localhost:${test_pg_port}/{TEST_DB_NAME}|" \
  #       -e "s/^DB_PORT=.*/DB_PORT=${test_pg_port}/" \
  #       -e "s|^AWS_ENDPOINT_URL=.*|AWS_ENDPOINT_URL=http://localhost:${test_ls_port}|" \
  #       -e "s|^SQS_ENDPOINT_URL=.*|SQS_ENDPOINT_URL=http://localhost:${test_ls_port}|" \
  #       -e "s|^AWS_S3_ENDPOINT_URL=.*|AWS_S3_ENDPOINT_URL=http://localhost:${test_ls_port}|" \
  #       "$(proj_path "$ROOT" "{project}")/.env.test" \
  #       > "$(proj_path "$worktree_dir" "{project}")/.env.test"
  #   fi
  #
  # {ENV_FILE_PROVISION} — SETUP fills this from the roster's env_files + port map.

  echo "Worktree ready: $worktree_dir"
  echo "Branch: $branch"
  echo "BE_PORT=${be_port}"
  echo "FE_PORT=${fe_port}"
  echo "TEST_PG_PORT=${test_pg_port}"
  echo "TEST_LS_PORT=${test_ls_port}"
  echo "PULSE_PORT=${pulse_port}"
  echo "WEB_PORT=${web_port}"
  echo "CORTEX_PORT=${cortex_port}"
}

cmd_remove() {
  local pipeline="$1"
  local branch="pipeline/${pipeline}"
  local worktree_dir="${ROOT}/.worktrees/${pipeline}"

  if [ -d "$worktree_dir" ]; then
    git worktree remove "$worktree_dir" --force 2>/dev/null || true
    echo "Worktree removed: $worktree_dir"
  else
    echo "No worktree found: $worktree_dir"
  fi

  git branch -d "$branch" 2>/dev/null || true

  # Free port allocation
  "$ALLOC" free "$pipeline"

  # Tear down the pipeline's docker test stack (containers + volumes).
  # No-op when the roster has no infra project ({INFRA_PROJECT} = "-").
  if [ "{INFRA_PROJECT}" != "-" ]; then
    make -C "${ROOT}/{INFRA_PROJECT}" {INFRA_NUKE_TARGET} PIPELINE="$pipeline" 2>/dev/null || true
  fi

  echo "Pipeline cleaned up: $pipeline"
}

cmd_prune() {
  # Remove ORPHANED worktree directories: present on disk but not a registered
  # git worktree AND with no active pipeline docs. Registered-but-inactive
  # worktrees are reported, never auto-removed (may hold uncommitted work).
  git -C "$ROOT" worktree prune 2>/dev/null || true  # drop git records for vanished dirs

  # Registered worktree BASENAMES — matched by name, not full path, so a symlinked or
  # canonicalized repo path can't misclassify a live worktree as orphaned.
  # Fail-safe: if git can't list worktrees, prune nothing rather than risk a live one.
  local registered
  if ! registered="$(git -C "$ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree /{n=split($2,a,"/"); print a[n]}')"; then
    echo "Prune skipped: could not list git worktrees."
    return 0
  fi

  local pruned=0
  for d in "${ROOT}/.worktrees"/*/; do
    [ -d "$d" ] || continue
    local name
    name="$(basename "$d")"
    [[ "$name" == .* ]] && continue

    if printf '%s\n' "$registered" | grep -qx "$name"; then
      # Registered worktree with no active pipeline → possible abandon. Report only.
      [ -d "${ROOT}/docs/dev/builds/${name}" ] || echo "REGISTERED-NO-DOCS: $name (registered worktree, no active pipeline — inspect; not auto-removed)"
      continue
    fi

    # Unregistered leftover directory
    if [ -d "${ROOT}/docs/dev/builds/${name}" ]; then
      echo "SKIP: $name (unregistered but has pipeline docs — inspect manually)"
      continue
    fi

    rm -rf "$d"
    "$ALLOC" free "$name" 2>/dev/null || true
    if [ "{INFRA_PROJECT}" != "-" ]; then
      make -C "${ROOT}/{INFRA_PROJECT}" {INFRA_NUKE_TARGET} PIPELINE="$name" 2>/dev/null || true
    fi
    echo "PRUNED: $name (orphaned worktree dir)"
    pruned=$((pruned + 1))
  done
  echo "Prune complete: $pruned orphaned worktree(s) removed."
}

cmd_list() {
  local pipeline="${1:-}"

  if [ -n "$pipeline" ]; then
    local worktree_dir="${ROOT}/.worktrees/${pipeline}"
    if [ ! -d "$worktree_dir" ]; then
      echo "No worktree for pipeline: $pipeline"
      return 0
    fi
    echo "=== Pipeline: $pipeline ==="
    echo "  Branch: pipeline/$pipeline"
    echo "  Path: $worktree_dir"
    if [ -f "$worktree_dir/.env.ports" ]; then
      echo "  Ports:"
      grep -E '^(BE_PORT|FE_PORT|TEST_PG_PORT|TEST_LS_PORT|PULSE_PORT|WEB_PORT|CORTEX_PORT)=' "$worktree_dir/.env.ports" | sed 's/^/    /'
    fi
  else
    echo "=== Active Pipelines ==="
    for d in "${ROOT}/.worktrees"/*/; do
      local name
      name="$(basename "$d")"
      # Skip hidden dirs (.ports, .merge-lock, etc.)
      [[ "$name" == .* ]] && continue
      [ -d "$d" ] || continue
      echo "  $name/ → pipeline/$name"
    done
  fi

  echo ""
  echo "=== Port Allocations ==="
  "$ALLOC" list
}

case "${1:-help}" in
  create)  cmd_create "${2:?pipeline required}" ;;
  remove)  cmd_remove "${2:?pipeline required}" ;;
  list)    cmd_list   "${2:-}" ;;
  prune)   cmd_prune ;;
  *)
    echo "Usage: $0 {create|remove|list|prune} <pipeline>"
    exit 1
    ;;
esac
